# Generated by Django 5.2.8 on 2025-11-08 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='专辑名称')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='封面图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='言论内容')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者（成员）')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '言论',
                'verbose_name_plural': '言论',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='巡回演出名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '巡回演出',
                'verbose_name_plural': '巡回演出',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='歌曲标题')),
                ('artist', models.CharField(default='五月天', max_length=100, verbose_name='艺术家')),
                ('file_path', models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'wav', 'm4a'])], verbose_name='音频文件')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长（秒）')),
                ('track_number', models.IntegerField(blank=True, null=True, verbose_name='曲目编号')),
                ('lyrics', models.TextField(blank=True, verbose_name='歌词')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='mayday_app.album', verbose_name='专辑')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['album', 'track_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('caption', models.TextField(blank=True, verbose_name='说明')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mayday_app.album', verbose_name='关联专辑')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mayday_app.tour', verbose_name='关联巡回演出')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TourVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场地名称')),
                ('date', models.DateField(verbose_name='演出日期')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='mayday_app.tour', verbose_name='巡回演出')),
            ],
            options={
                'verbose_name': '演出场地',
                'verbose_name_plural': '演出场地',
                'ordering': ['date'],
            },
        ),
    ]
