# Generated by Django 5.2.8 on 2025-11-08 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayday_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='原始文件路径'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'wav', 'm4a'])], verbose_name='音频文件（上传）'),
        ),
    ]
