# Generated by Django 5.2.8 on 2025-11-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayday_app', '0003_playlist_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_initial',
            field=models.CharField(blank=True, max_length=1, verbose_name='歌手首字母'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_pinyin',
            field=models.CharField(blank=True, max_length=255, verbose_name='歌手拼音'),
        ),
    ]
