# Generated by Django 5.2.8 on 2025-11-18 18:52

from django.db import migrations


def populate_pinyin_fields(apps, schema_editor):
    """填充歌手拼音和首字母字段"""
    try:
        from pypinyin import lazy_pinyin, Style
        
        Song = apps.get_model('mayday_app', 'Song')
        
        # 获取所有不重复的歌手
        artists = Song.objects.values_list('artist', flat=True).distinct()
        
        for artist in artists:
            if not artist:
                continue
            
            # 生成拼音
            pinyin_list = lazy_pinyin(artist, style=Style.NORMAL)
            pinyin = ''.join(pinyin_list)
            
            # 获取首字母（取第一个字符的拼音首字母）
            if pinyin:
                initial = pinyin[0].upper()
            else:
                # 如果是英文，直接取首字母
                initial = artist[0].upper() if artist else ''
            
            # 更新所有该歌手的歌曲
            Song.objects.filter(artist=artist).update(
                artist_pinyin=pinyin,
                artist_initial=initial
            )
    except ImportError:
        # 如果pypinyin未安装，跳过
        print("Warning: pypinyin not installed, skipping pinyin population")


def reverse_populate_pinyin_fields(apps, schema_editor):
    """反向操作：清空拼音字段"""
    Song = apps.get_model('mayday_app', 'Song')
    Song.objects.all().update(artist_pinyin='', artist_initial='')


class Migration(migrations.Migration):

    dependencies = [
        ('mayday_app', '0004_song_artist_initial_song_artist_pinyin'),
    ]

    operations = [
        migrations.RunPython(populate_pinyin_fields, reverse_populate_pinyin_fields),
    ]
