# Generated by Django 5.2.8 on 2026-08-12 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayday_app', '0007_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', '演示'), ('stripe', 'Stripe')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=20)),
                ('amount_cents', models.PositiveIntegerField(default=990, verbose_name='金额（分）')),
                ('currency', models.CharField(default='cny', max_length=10, verbose_name='币种')),
                ('days', models.PositiveIntegerField(default=30, verbose_name='开通天数')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='外部单号')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='已履约开通')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员订单',
                'verbose_name_plural': '会员订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
